//! Bidirectional Engineering Change Order (ECO) Engine.
//!
//! Performs deep structural diffing between the authoritative schematic Netlist
//! and physical PCB layout state, synthesizing atomic ECO actions (add/remove/rename nets,
//! add/remove footprints, re-assign pins/pads, update designators).

use std::collections::{HashMap, HashSet};
use oxide_types::net::Netlist;
use oxide_types::pcb::{Footprint, PadNet, PcbBoard, Point};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Atomic ECO action to synchronize schematic and PCB.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum EcoAction {
    /// Add a missing footprint to the PCB layout.
    AddFootprint {
        reference: String,
        value: String,
        footprint_id: String,
        suggested_pos: Point,
    },
    /// Remove an obsolete footprint from the PCB layout.
    RemoveFootprint {
        reference: String,
        uuid: Uuid,
    },
    /// Update footprint metadata or library reference.
    UpdateFootprint {
        reference: String,
        old_value: String,
        new_value: String,
        old_footprint_id: String,
        new_footprint_id: String,
    },
    /// Add a new electrical net.
    AddNet {
        name: String,
        net_id: u32,
    },
    /// Remove an unused net.
    RemoveNet {
        name: String,
        net_id: u32,
    },
    /// Reconnect or assign a pad on a footprint to a net.
    AssignPadNet {
        reference: String,
        pad_number: String,
        old_net: Option<String>,
        new_net: Option<String>,
        new_net_id: u32,
    },
    /// Rename a component designator.
    RenameDesignator {
        old_reference: String,
        new_reference: String,
    },
    /// Swap two pin/net connections on a component (Directive §5.3).
    PinSwap {
        component_reference: String,
        pin_a: String,
        pin_b: String,
        net_a: String,
        net_b: String,
    },
}

/// ECO Diff Report generated by comparing schematic netlist and PCB board.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EcoReport {
    pub actions: Vec<EcoAction>,
}

impl EcoReport {
    pub fn is_empty(&self) -> bool {
        self.actions.is_empty()
    }

    pub fn len(&self) -> usize {
        self.actions.len()
    }
}

/// Bidirectional ECO Diff and Synchronization Engine.
pub struct EcoEngine;

impl EcoEngine {
    /// Generate Forward ECO (Schematic -> PCB).
    /// Computes changes required on the PCB to match the schematic netlist and symbols.
    pub fn diff_schematic_to_pcb(
        netlist: &Netlist,
        board: &PcbBoard,
        schematic_components: &[(String, String, String)], // (reference, value, footprint_id)
    ) -> EcoReport {
        let mut actions = Vec::new();

        // 1. Component presence diff
        let pcb_fps: HashMap<&str, &Footprint> = board
            .footprints
            .iter()
            .map(|fp| (fp.reference.as_str(), fp))
            .collect();

        let mut sch_ref_set = HashSet::new();

        let mut next_x = 10.0;
        let mut next_y = 10.0;

        for (ref_des, val, fp_id) in schematic_components {
            sch_ref_set.insert(ref_des.as_str());
            match pcb_fps.get(ref_des.as_str()) {
                None => {
                    // Missing on PCB -> Add
                    actions.push(EcoAction::AddFootprint {
                        reference: ref_des.clone(),
                        value: val.clone(),
                        footprint_id: fp_id.clone(),
                        suggested_pos: Point { x: next_x, y: next_y },
                    });
                    next_x += 15.0;
                    if next_x > 150.0 {
                        next_x = 10.0;
                        next_y += 15.0;
                    }
                }
                Some(existing_fp) => {
                    // Check if value or footprint changed
                    if existing_fp.value != *val || existing_fp.footprint_id != *fp_id {
                        actions.push(EcoAction::UpdateFootprint {
                            reference: ref_des.clone(),
                            old_value: existing_fp.value.clone(),
                            new_value: val.clone(),
                            old_footprint_id: existing_fp.footprint_id.clone(),
                            new_footprint_id: fp_id.clone(),
                        });
                    }
                }
            }
        }

        // Check for orphaned footprints on PCB
        for fp in &board.footprints {
            if !sch_ref_set.contains(fp.reference.as_str()) {
                actions.push(EcoAction::RemoveFootprint {
                    reference: fp.reference.clone(),
                    uuid: fp.uuid,
                });
            }
        }

        // 2. Net connectivity diff
        // Build map of expected (RefDes, Pin) -> NetName & NetID from Schematic Netlist
        let mut expected_connections: HashMap<(&str, &str), (&str, u32)> = HashMap::new();
        for net in &netlist.nets {
            for terminal in &net.terminals {
                expected_connections.insert(
                    (terminal.reference.as_str(), terminal.pin.as_str()),
                    (net.name.as_str(), net.id.0),
                );
            }
        }

        // Inspect actual connections on PCB pads
        for fp in &board.footprints {
            for pad in &fp.pads {
                let actual_net_name = pad.net.as_ref().map(|n| n.name.as_str());
                let expected = expected_connections.get(&(fp.reference.as_str(), pad.number.as_str()));

                match (actual_net_name, expected) {
                    (Some(act), Some((exp_name, exp_id))) if act != *exp_name => {
                        actions.push(EcoAction::AssignPadNet {
                            reference: fp.reference.clone(),
                            pad_number: pad.number.clone(),
                            old_net: Some(act.to_string()),
                            new_net: Some(exp_name.to_string()),
                            new_net_id: *exp_id,
                        });
                    }
                    (None, Some((exp_name, exp_id))) => {
                        actions.push(EcoAction::AssignPadNet {
                            reference: fp.reference.clone(),
                            pad_number: pad.number.clone(),
                            old_net: None,
                            new_net: Some(exp_name.to_string()),
                            new_net_id: *exp_id,
                        });
                    }
                    (Some(act), None) => {
                        // Pad should be disconnected / unconnected
                        actions.push(EcoAction::AssignPadNet {
                            reference: fp.reference.clone(),
                            pad_number: pad.number.clone(),
                            old_net: Some(act.to_string()),
                            new_net: None,
                            new_net_id: 0,
                        });
                    }
                    _ => {}
                }
            }
        }

        EcoReport { actions }
    }

    /// Apply an ECO Report directly onto a PCB Board model.
    pub fn apply_eco(board: &mut PcbBoard, report: &EcoReport) {
        for action in &report.actions {
            match action {
                EcoAction::AddFootprint {
                    reference,
                    value,
                    footprint_id,
                    suggested_pos,
                } => {
                    board.footprints.push(Footprint {
                        uuid: Uuid::new_v4(),
                        reference: reference.clone(),
                        value: value.clone(),
                        footprint_id: footprint_id.clone(),
                        position: *suggested_pos,
                        rotation: 0.0,
                        layer: "F.Cu".to_string(),
                        locked: false,
                        pads: Vec::new(),
                        graphics: Vec::new(),
                        properties: Vec::new(),
                    });
                }
                EcoAction::RemoveFootprint { uuid, .. } => {
                    board.footprints.retain(|fp| fp.uuid != *uuid);
                }
                EcoAction::UpdateFootprint {
                    reference,
                    new_value,
                    new_footprint_id,
                    ..
                } => {
                    if let Some(fp) = board.footprints.iter_mut().find(|f| f.reference == *reference) {
                        fp.value = new_value.clone();
                        fp.footprint_id = new_footprint_id.clone();
                    }
                }
                #[allow(clippy::collapsible_if)]
                EcoAction::AssignPadNet {
                    reference,
                    pad_number,
                    new_net,
                    new_net_id,
                    ..
                } => {
                    if let Some(fp) = board.footprints.iter_mut().find(|f| f.reference == *reference) {
                        if let Some(pad) = fp.pads.iter_mut().find(|p| p.number == *pad_number) {
                            pad.net = new_net.as_ref().map(|name| PadNet {
                                number: *new_net_id,
                                name: name.clone(),
                            });
                        }
                    }
                }
                EcoAction::RenameDesignator {
                    old_reference,
                    new_reference,
                } => {
                    if let Some(fp) = board.footprints.iter_mut().find(|f| f.reference == *old_reference) {
                        fp.reference = new_reference.clone();
                    }
                }
                _ => {}
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxide_types::net::{Net, NetId, Terminal};
    use oxide_types::pcb::{Pad, PadShape, PadType};

    #[test]
    fn test_eco_diff_and_apply() {
        let mut board = PcbBoard::default();

        let netlist = Netlist::from_nets(vec![
            Net {
                id: NetId(1),
                name: "GND".to_string(),
                class: None,
                wires: vec![],
                junctions: vec![],
                terminals: vec![
                    Terminal::new(
                        Uuid::new_v4(),
                        "R1",
                        "1",
                    ),
                ],
            },
        ]);

        let sch_components = vec![
            ("R1".to_string(), "10k".to_string(), "R_0603".to_string()),
            ("C1".to_string(), "100nF".to_string(), "C_0402".to_string()),
        ];

        // 1. Initial diff should detect missing R1 and C1
        let report = EcoEngine::diff_schematic_to_pcb(&netlist, &board, &sch_components);
        assert_eq!(report.actions.len(), 2);

        // 2. Apply ECO
        EcoEngine::apply_eco(&mut board, &report);
        assert_eq!(board.footprints.len(), 2);

        // 3. Add pad to R1 without net and verify PadNet assignment action
        board.footprints[0].pads.push(Pad {
            uuid: Uuid::new_v4(),
            number: "1".to_string(),
            pad_type: PadType::Smd,
            shape: PadShape::Rect,
            position: Point { x: 0.0, y: 0.0 },
            size: Point { x: 1.0, y: 1.0 },
            drill: None,
            layers: vec!["F.Cu".to_string()],
            net: None,
            roundrect_ratio: 0.0,
        });

        let pad_report = EcoEngine::diff_schematic_to_pcb(&netlist, &board, &sch_components);
        assert_eq!(pad_report.actions.len(), 1);
        match &pad_report.actions[0] {
            EcoAction::AssignPadNet { reference, pad_number, new_net, .. } => {
                assert_eq!(reference, "R1");
                assert_eq!(pad_number, "1");
                assert_eq!(new_net.as_deref(), Some("GND"));
            }
            _ => panic!("Expected AssignPadNet action"),
        }

        // Apply pad assignment
        EcoEngine::apply_eco(&mut board, &pad_report);
        assert_eq!(board.footprints[0].pads[0].net.as_ref().unwrap().name, "GND");
    }
}
