//! PSpice simulation deck generator.
//!
//! Translates schematic netlists, placed symbols, and library `SimModel`s
//! into a clean, valid PSpice/SPICE netlist deck.

use std::collections::{HashMap, HashSet};
use oxide_library::SimModel;
use oxide_types::net::Netlist;
use oxide_types::schematic::SchematicSheet;
use oxide_types::sim::{AcSweepType, AnalysisKind, Probe, SimulationConfig};

/// Builder that generates a complete PSpice simulation deck (`.cir`).
pub struct PSpiceDeckBuilder<'a> {
    netlist: &'a Netlist,
    sheets: &'a [SchematicSheet],
    models: &'a HashMap<String, SimModel>,
    config: &'a SimulationConfig,
    title: String,
}

impl<'a> PSpiceDeckBuilder<'a> {
    pub fn new(
        netlist: &'a Netlist,
        sheets: &'a [SchematicSheet],
        models: &'a HashMap<String, SimModel>,
        config: &'a SimulationConfig,
    ) -> Self {
        Self {
            netlist,
            sheets,
            models,
            config,
            title: "Oxide EDA PSpice Simulation".to_string(),
        }
    }

    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = title.into();
        self
    }

    /// Build the full PSpice netlist deck as a string.
    pub fn build(&self) -> String {
        let mut out = String::new();

        // 1. Header & Title (First line of SPICE deck is always title)
        out.push_str(&format!("* {}\n", self.title));
        out.push_str("* Generated by Oxide EDA PSpice Deck Generator\n");
        out.push_str(".PARAM pi=3.141592653589793\n\n");

        // 2. Compatibility & Options
        out.push_str("* Simulator Options\n");
        out.push_str(&format!(
            ".OPTIONS TNOM={:.1} RELTOL={:.4e} VNTOL={:.4e} ABSTOL={:.4e}\n\n",
            self.config.temp_c, self.config.reltol, self.config.vntol, self.config.abstol
        ));

        // 3. Build Node Mapping (resolve reference designator + pin to net name, mapping Ground to 0)
        let pin_to_net = self.build_pin_to_node_map();

        // 4. Instantiate Components from Schematic Sheets
        out.push_str("* Circuit Components\n");
        let mut subckts_to_include: HashSet<String> = HashSet::new();
        let mut subckt_bodies: Vec<String> = Vec::new();

        for sheet in self.sheets {
            for sym in &sheet.symbols {
                if sym.exclude_from_sim || sym.dnp {
                    continue;
                }

                let refdes = sym.reference.trim();
                if refdes.is_empty() {
                    continue;
                }

                let upper_ref = refdes.to_ascii_uppercase();
                let value_str = sanitize_spice_value(&sym.value);

                // Check if this component has a bound PSpice/SPICE model
                if let Some(model) = self.find_model_for_symbol(refdes, &sym.value, &sym.lib_id) {
                    // Subcircuit instantiation: `X<ref> <pin_nodes...> <subckt_name>`
                    let mut node_tokens = Vec::new();

                    // Map pins in model's declared node order
                    if !model.default_node_map.is_empty() {
                        for (_pin_idx, pin_name) in &model.default_node_map {
                            let node = pin_to_net
                                .get(&(refdes.to_string(), pin_name.clone()))
                                .cloned()
                                .unwrap_or_else(|| "0".to_string());
                            node_tokens.push(node);
                        }
                    } else {
                        // Fallback: iterate symbol pins by index 1..N
                        for i in 1..=8 {
                            if let Some(node) = pin_to_net.get(&(refdes.to_string(), i.to_string())) {
                                node_tokens.push(node.clone());
                            }
                        }
                    }

                    if !node_tokens.is_empty() {
                        let subckt_name = sanitize_identifier(&model.name);
                        out.push_str(&format!(
                            "X{} {} {}\n",
                            refdes,
                            node_tokens.join(" "),
                            subckt_name
                        ));

                        if subckts_to_include.insert(subckt_name.clone()) {
                            subckt_bodies.push(model.body.clone());
                        }
                        continue;
                    }
                }

                // Standard SPICE Primitives
                if upper_ref.starts_with('R') {
                    let n1 = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let n2 = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{} {} {} {}\n", refdes, n1, n2, value_str));
                } else if upper_ref.starts_with('C') {
                    let n1 = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let n2 = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{} {} {} {}\n", refdes, n1, n2, value_str));
                } else if upper_ref.starts_with('L') {
                    let n1 = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let n2 = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{} {} {} {}\n", refdes, n1, n2, value_str));
                } else if upper_ref.starts_with('D') {
                    let n1 = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let n2 = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let model_name = if sym.value.is_empty() { "DMOD" } else { &sym.value };
                    out.push_str(&format!("{} {} {} {}\n", refdes, n1, n2, model_name));
                } else if upper_ref.starts_with('V') {
                    let np = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let nn = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{} {} {} DC {}\n", refdes, np, nn, value_str));
                } else if upper_ref.starts_with('I') {
                    let np = pin_to_net.get(&(refdes.to_string(), "1".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    let nn = pin_to_net.get(&(refdes.to_string(), "2".to_string())).cloned().unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{} {} {} DC {}\n", refdes, np, nn, value_str));
                }
            }
        }

        // 5. Append Subcircuits and Model Cards
        if !subckt_bodies.is_empty() {
            out.push_str("\n* Subcircuit & Model Definitions\n");
            for body in &subckt_bodies {
                out.push_str(body);
                if !body.ends_with('\n') {
                    out.push('\n');
                }
                out.push('\n');
            }
        }

        // 6. Analysis Directives
        out.push_str("* Simulation Directives\n");
        match &self.config.analysis {
            AnalysisKind::Transient {
                start_time,
                stop_time,
                step_time,
                max_step,
                uic,
            } => {
                let max_s = max_step.map(|m| format!(" {:.4e}", m)).unwrap_or_default();
                let uic_s = if *uic { " UIC" } else { "" };
                out.push_str(&format!(
                    ".TRAN {:.4e} {:.4e} {:.4e}{}{}\n",
                    step_time, stop_time, start_time, max_s, uic_s
                ));
            }
            AnalysisKind::Ac {
                sweep_type,
                points,
                start_freq,
                stop_freq,
            } => {
                let sw_str = match sweep_type {
                    AcSweepType::Decade => "DEC",
                    AcSweepType::Octave => "OCT",
                    AcSweepType::Linear => "LIN",
                };
                out.push_str(&format!(
                    ".AC {} {} {:.4e} {:.4e}\n",
                    sw_str, points, start_freq, stop_freq
                ));
            }
            AnalysisKind::Dc {
                source,
                start,
                stop,
                step,
                nested,
            } => {
                if let Some(n) = nested {
                    out.push_str(&format!(
                        ".DC {} {:.4e} {:.4e} {:.4e} {} {:.4e} {:.4e} {:.4e}\n",
                        source, start, stop, step, n.source, n.start, n.stop, n.step
                    ));
                } else {
                    out.push_str(&format!(
                        ".DC {} {:.4e} {:.4e} {:.4e}\n",
                        source, start, stop, step
                    ));
                }
            }
            AnalysisKind::OperatingPoint => {
                out.push_str(".OP\n");
            }
            AnalysisKind::Parametric {
                param_name,
                sweep_values,
            } => {
                let vals = sweep_values.iter().map(|v| format!("{:.4e}", v)).collect::<Vec<_>>().join(" ");
                out.push_str(&format!(".STEP PARAM {} LIST {}\n", param_name, vals));
            }
            AnalysisKind::Temperature { temps } => {
                let vals = temps.iter().map(|t| format!("{:.1}", t)).collect::<Vec<_>>().join(" ");
                out.push_str(&format!(".TEMP {}\n", vals));
            }
        }

        // 7. Output Probes
        if !self.config.probes.is_empty() {
            let mut probe_tokens = Vec::new();
            for p in &self.config.probes {
                match p {
                    Probe::Voltage { net_name, .. } => {
                        let node = sanitize_node_name(net_name);
                        probe_tokens.push(format!("V({})", node));
                    }
                    Probe::Current { component_ref, pin } => {
                        probe_tokens.push(format!("I({}:{})", component_ref, pin));
                    }
                    Probe::Differential { pos_net, neg_net } => {
                        let n1 = sanitize_node_name(pos_net);
                        let n2 = sanitize_node_name(neg_net);
                        probe_tokens.push(format!("V({},{})", n1, n2));
                    }
                }
            }
            out.push_str(&format!(".PROBE {}\n", probe_tokens.join(" ")));
        } else {
            out.push_str(".PROBE V\n");
        }

        // 8. End
        out.push_str(".END\n");

        out
    }

    fn build_pin_to_node_map(&self) -> HashMap<(String, String), String> {
        let mut map = HashMap::new();

        for net in &self.netlist.nets {
            let node_name = sanitize_node_name(&net.name);
            for terminal in &net.terminals {
                map.insert((terminal.reference.clone(), terminal.pin.clone()), node_name.clone());
            }
        }

        map
    }

    fn find_model_for_symbol(&self, _refdes: &str, value: &str, lib_id: &str) -> Option<&SimModel> {
        if let Some(m) = self.models.get(value) {
            return Some(m);
        }
        if let Some(m) = self.models.get(lib_id) {
            return Some(m);
        }
        None
    }
}

/// Sanitize net names into valid SPICE node identifiers (mapping GND variants to 0).
fn sanitize_node_name(name: &str) -> String {
    let trimmed = name.trim();
    let upper = trimmed.to_ascii_uppercase();
    if upper == "GND" || upper == "0" || upper == "AGND" || upper == "DGND" || upper == "PGND" {
        return "0".to_string();
    }

    trimmed
        .replace([' ', '/', '\\', '.', '-', '+'], "_")
        .trim_matches('_')
        .to_string()
}

fn sanitize_identifier(name: &str) -> String {
    name.replace([' ', '/', '\\', '.', '-'], "_")
}

/// Convert user schematic values (e.g. 10k, 100n, 10u, 1MEG) to valid SPICE strings.
fn sanitize_spice_value(val: &str) -> String {
    let trimmed = val.trim();
    if trimmed.is_empty() {
        return "1k".to_string();
    }

    let upper = trimmed.to_ascii_uppercase();
    // Handle the classic SPICE 1M vs 1MEG distinction
    if upper.ends_with("MEG") || upper.ends_with("MOHM") {
        return trimmed.to_string();
    }
    if upper.ends_with("M") && !upper.ends_with("MM") {
        // If it's pure number followed by M (e.g. 1M or 10M), in EDA users often mean Mega
        // but in SPICE M is milli. Preserve user input or expand:
        return format!("{}MEG", &trimmed[..trimmed.len() - 1]);
    }

    trimmed.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxide_types::net::{Net, NetId, Terminal};
    use oxide_types::schematic::Symbol;
    use uuid::Uuid;

    #[test]
    fn build_rc_circuit_deck() {
        let netlist = Netlist {
            nets: vec![
                Net {
                    id: NetId(1),
                    name: "IN".to_string(),
                    class: None,
                    wires: Vec::new(),
                    junctions: Vec::new(),
                    terminals: vec![
                        Terminal { symbol: Uuid::nil(), reference: "V1".to_string(), pin: "1".to_string(), internal_delay_ps: 0.0 },
                        Terminal { symbol: Uuid::nil(), reference: "R1".to_string(), pin: "1".to_string(), internal_delay_ps: 0.0 },
                    ],
                },
                Net {
                    id: NetId(2),
                    name: "OUT".to_string(),
                    class: None,
                    wires: Vec::new(),
                    junctions: Vec::new(),
                    terminals: vec![
                        Terminal { symbol: Uuid::nil(), reference: "R1".to_string(), pin: "2".to_string(), internal_delay_ps: 0.0 },
                        Terminal { symbol: Uuid::nil(), reference: "C1".to_string(), pin: "1".to_string(), internal_delay_ps: 0.0 },
                    ],
                },
                Net {
                    id: NetId(3),
                    name: "GND".to_string(),
                    class: None,
                    wires: Vec::new(),
                    junctions: Vec::new(),
                    terminals: vec![
                        Terminal { symbol: Uuid::nil(), reference: "V1".to_string(), pin: "2".to_string(), internal_delay_ps: 0.0 },
                        Terminal { symbol: Uuid::nil(), reference: "C1".to_string(), pin: "2".to_string(), internal_delay_ps: 0.0 },
                    ],
                },
            ],
            xsignals: Vec::new(),
        };

        let mut sym_v1 = Symbol::empty();
        sym_v1.reference = "V1".to_string();
        sym_v1.value = "5.0".to_string();

        let mut sym_r1 = Symbol::empty();
        sym_r1.reference = "R1".to_string();
        sym_r1.value = "1k".to_string();

        let mut sym_c1 = Symbol::empty();
        sym_c1.reference = "C1".to_string();
        sym_c1.value = "100n".to_string();

        let sheet = SchematicSheet {
            uuid: Uuid::nil(),
            version: 1,
            generator: "Oxide".to_string(),
            generator_version: "1.0".to_string(),
            paper_size: "A4".to_string(),
            root_sheet_page: "1".to_string(),
            symbols: vec![sym_v1, sym_r1, sym_c1],
            wires: Vec::new(),
            junctions: Vec::new(),
            labels: Vec::new(),
            child_sheets: Vec::new(),
            no_connects: Vec::new(),
            text_notes: Vec::new(),
            buses: Vec::new(),
            bus_entries: Vec::new(),
            drawings: Vec::new(),
            no_erc_directives: Vec::new(),
            title_block: HashMap::new(),
            lib_symbols: HashMap::new(),
        };

        let config = SimulationConfig {
            analysis: AnalysisKind::Transient {
                start_time: 0.0,
                stop_time: 1e-3,
                step_time: 1e-6,
                max_step: None,
                uic: false,
            },
            probes: vec![Probe::Voltage { net_name: "OUT".to_string(), net_id: Some(2) }],
            ..Default::default()
        };

        let models = HashMap::new();
        let sheets = vec![sheet];
        let builder = PSpiceDeckBuilder::new(&netlist, &sheets, &models, &config);
        let deck = builder.build();

        assert!(deck.contains("R1 IN OUT 1k"));
        assert!(deck.contains("C1 OUT 0 100n"));
        assert!(deck.contains("V1 IN 0 DC 5.0"));
        assert!(deck.contains(".TRAN"));
        assert!(deck.contains(".PROBE V(OUT)"));
    }
}
