//! Detailed violation reports generated by rule validation.

use serde::{Deserialize, Serialize};

use crate::scope::RuleScope;

/// Categories of design rule violations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleViolationType {
    WidthTooSmall,
    WidthTooLarge,
    ClearanceViolation,
    ImpedanceOutOfTolerance,
    LengthMismatch,
    ViaDrillTooSmall,
    ViaDiameterTooSmall,
    HdiViolation,
}

/// Detailed design rule violation report with actionable delta metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RuleViolation {
    pub violation_type: RuleViolationType,
    pub message: String,
    pub scope: RuleScope,
    pub required_value: String,
    pub actual_value: String,
    pub location: Option<(f64, f64)>,
    pub object_ids: Vec<String>,
}

impl RuleViolation {
    pub fn width_too_small(
        net: &str,
        scope: RuleScope,
        min_width_microns: i64,
        actual_width_microns: i64,
    ) -> Self {
        let req_mm = min_width_microns as f64 / 1000.0;
        let act_mm = actual_width_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::WidthTooSmall,
            message: format!(
                "Width violation on net '{net}': trace width is {act_mm:.3}mm ({actual_width_microns}µm), rule requires minimum {req_mm:.3}mm ({min_width_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![net.to_string()],
        }
    }

    pub fn clearance_violation(
        net_a: &str,
        net_b: &str,
        scope: RuleScope,
        min_clearance_microns: i64,
        actual_distance_microns: i64,
    ) -> Self {
        let req_mm = min_clearance_microns as f64 / 1000.0;
        let act_mm = actual_distance_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::ClearanceViolation,
            message: format!(
                "Clearance violation between net '{net_a}' and '{net_b}': distance is {act_mm:.3}mm ({actual_distance_microns}µm), rule requires minimum {req_mm:.3}mm ({min_clearance_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![net_a.to_string(), net_b.to_string()],
        }
    }
}
