//! Detailed violation reports generated by rule validation.

use serde::{Deserialize, Serialize};

use crate::scope::RuleScope;

/// Categories of design rule violations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleViolationType {
    WidthTooSmall,
    WidthTooLarge,
    ClearanceViolation,
    ImpedanceOutOfTolerance,
    LengthMismatch,
    ViaDrillTooSmall,
    ViaDiameterTooSmall,
    HdiViolation,
    SolderMaskSliverTooSmall,
    SilkscreenClearanceViolation,
    NetAntennaExceeded,
    ReturnPathSplitCrossing,
    ComponentClearanceViolation,
    UnpermittedRoutingLayer,
    PhaseSkewViolation,
}

/// Detailed design rule violation report with actionable delta metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RuleViolation {
    pub violation_type: RuleViolationType,
    pub message: String,
    pub scope: RuleScope,
    pub required_value: String,
    pub actual_value: String,
    pub location: Option<(f64, f64)>,
    pub object_ids: Vec<String>,
}

impl RuleViolation {
    pub fn width_too_small(
        net: &str,
        scope: RuleScope,
        min_width_microns: i64,
        actual_width_microns: i64,
    ) -> Self {
        let req_mm = min_width_microns as f64 / 1000.0;
        let act_mm = actual_width_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::WidthTooSmall,
            message: format!(
                "Width violation on net '{net}': trace width is {act_mm:.3}mm ({actual_width_microns}µm), rule requires minimum {req_mm:.3}mm ({min_width_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![net.to_string()],
        }
    }

    pub fn clearance_violation(
        net_a: &str,
        net_b: &str,
        scope: RuleScope,
        min_clearance_microns: i64,
        actual_distance_microns: i64,
    ) -> Self {
        let req_mm = min_clearance_microns as f64 / 1000.0;
        let act_mm = actual_distance_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::ClearanceViolation,
            message: format!(
                "Clearance violation between net '{net_a}' and '{net_b}': distance is {act_mm:.3}mm ({actual_distance_microns}µm), rule requires minimum {req_mm:.3}mm ({min_clearance_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![net_a.to_string(), net_b.to_string()],
        }
    }

    pub fn solder_mask_sliver_too_small(
        object_id: &str,
        scope: RuleScope,
        min_sliver_microns: i64,
        actual_sliver_microns: i64,
    ) -> Self {
        let req_mm = min_sliver_microns as f64 / 1000.0;
        let act_mm = actual_sliver_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::SolderMaskSliverTooSmall,
            message: format!(
                "Solder mask sliver violation on '{object_id}': bridge is {act_mm:.3}mm ({actual_sliver_microns}µm), rule requires minimum {req_mm:.3}mm ({min_sliver_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![object_id.to_string()],
        }
    }

    pub fn silkscreen_clearance_violation(
        object_a: &str,
        object_b: &str,
        scope: RuleScope,
        min_clearance_microns: i64,
        actual_distance_microns: i64,
    ) -> Self {
        let req_mm = min_clearance_microns as f64 / 1000.0;
        let act_mm = actual_distance_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::SilkscreenClearanceViolation,
            message: format!(
                "Silkscreen clearance violation between '{object_a}' and '{object_b}': distance is {act_mm:.3}mm ({actual_distance_microns}µm), rule requires minimum {req_mm:.3}mm ({min_clearance_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![object_a.to_string(), object_b.to_string()],
        }
    }

    pub fn net_antenna_exceeded(
        net: &str,
        scope: RuleScope,
        max_stub_microns: i64,
        actual_stub_microns: i64,
    ) -> Self {
        let req_mm = max_stub_microns as f64 / 1000.0;
        let act_mm = actual_stub_microns as f64 / 1000.0;
        Self {
            violation_type: RuleViolationType::NetAntennaExceeded,
            message: format!(
                "Net antenna (dangling stub) on net '{net}': stub length is {act_mm:.3}mm ({actual_stub_microns}µm), rule allows maximum {req_mm:.3}mm ({max_stub_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![net.to_string()],
        }
    }

    pub fn return_path_split_crossing(
        net: &str,
        net_class: &str,
        plane_net: &str,
        location: Option<(f64, f64)>,
    ) -> Self {
        Self {
            violation_type: RuleViolationType::ReturnPathSplitCrossing,
            message: format!(
                "High-speed return path violation on net '{net}' (class '{net_class}'): trace crosses split/gap in reference plane '{plane_net}'"
            ),
            scope: RuleScope::NetClass(net_class.to_string()),
            required_value: "Continuous reference plane".to_string(),
            actual_value: format!("Split crossing plane '{plane_net}'"),
            location,
            object_ids: vec![net.to_string(), plane_net.to_string()],
        }
    }

    pub fn component_clearance_violation(
        designator_a: &str,
        designator_b: &str,
        scope: RuleScope,
        min_clearance_microns: i64,
        actual_distance_microns: i64,
        is_vertical: bool,
    ) -> Self {
        let req_mm = min_clearance_microns as f64 / 1000.0;
        let act_mm = actual_distance_microns as f64 / 1000.0;
        let dim_str = if is_vertical { "vertical (Z)" } else { "horizontal (X/Y)" };
        Self {
            violation_type: RuleViolationType::ComponentClearanceViolation,
            message: format!(
                "Component clearance violation between '{designator_a}' and '{designator_b}': {dim_str} distance is {act_mm:.3}mm ({actual_distance_microns}µm), rule requires minimum {req_mm:.3}mm ({min_clearance_microns}µm)"
            ),
            scope,
            required_value: format!("{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![designator_a.to_string(), designator_b.to_string()],
        }
    }

    pub fn unpermitted_routing_layer(
        net: &str,
        scope: RuleScope,
        layer: &str,
        permitted_layers: &[String],
    ) -> Self {
        Self {
            violation_type: RuleViolationType::UnpermittedRoutingLayer,
            message: format!(
                "Routing layer violation on net '{net}': layer '{layer}' is not allowed (permitted: [{}])",
                permitted_layers.join(", ")
            ),
            scope,
            required_value: permitted_layers.join(", "),
            actual_value: layer.to_string(),
            location: None,
            object_ids: vec![net.to_string()],
        }
    }

    pub fn phase_skew_violation(
        net_class: &str,
        pair_or_bus: &str,
        max_skew_microns: i64,
        actual_skew_microns: i64,
        is_intra_pair: bool,
    ) -> Self {
        let req_mm = max_skew_microns as f64 / 1000.0;
        let act_mm = actual_skew_microns as f64 / 1000.0;
        let skew_type = if is_intra_pair { "intra-pair phase" } else { "inter-pair bus" };
        Self {
            violation_type: RuleViolationType::PhaseSkewViolation,
            message: format!(
                "Differential pair {skew_type} skew violation on '{pair_or_bus}' (class '{net_class}'): skew is {act_mm:.3}mm ({actual_skew_microns}µm), tolerance is ±{req_mm:.3}mm (±{max_skew_microns}µm)"
            ),
            scope: RuleScope::NetClass(net_class.to_string()),
            required_value: format!("±{req_mm:.3}mm"),
            actual_value: format!("{act_mm:.3}mm"),
            location: None,
            object_ids: vec![pair_or_bus.to_string()],
        }
    }
}
