//! Intermediate Representation (IR) for AI-generated circuit designs and prompt intents.

use serde::{Deserialize, Serialize};

/// Supported electronic component distributors for real-part lookup and validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Distributor {
    Lcsc,
    DigiKey,
    Mouser,
    Jep,
}

/// A requested electronic component generated by the LLM from natural language.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ComponentRequest {
    /// Function or generic description (e.g. "ESP32-S3-WROOM-1", "USB Type-C 16-Pin Receptacle", "TP4056 LiPo Charger").
    pub function: String,
    /// Reference designator prefix (e.g. "U", "C", "R", "J").
    pub designator_prefix: String,
    /// Suggested or verified Manufacturer Part Number (MPN).
    #[serde(default)]
    pub verified_part_number: Option<String>,
    /// Preferred distributor if specified.
    #[serde(default)]
    pub preferred_distributor: Option<Distributor>,
    /// Footprint package suggestion (e.g. "QFN-32", "0603", "TYPE-C-16P").
    #[serde(default)]
    pub footprint_hint: Option<String>,
    /// Verified stock quantity from distributor API.
    #[serde(default)]
    pub in_stock_quantity: Option<u64>,
}

impl ComponentRequest {
    pub fn new(function: impl Into<String>, designator_prefix: impl Into<String>) -> Self {
        Self {
            function: function.into(),
            designator_prefix: designator_prefix.into(),
            verified_part_number: None,
            preferred_distributor: None,
            footprint_hint: None,
            in_stock_quantity: None,
        }
    }
}

/// A connection intent linking two component pins with a named net.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ConnectionIntent {
    /// Net identifier (e.g. "USB_D+", "VBUS", "I2C_SDA", "GND").
    pub net_name: String,
    /// Source pin: (Component Ref / Index, Pin Name or Number)
    pub from: (String, String),
    /// Destination pin: (Component Ref / Index, Pin Name or Number)
    pub to: (String, String),
}

/// Structured engineering intent extracted from natural language prompts.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CircuitIntent {
    /// Natural language prompt that initiated this generation.
    pub prompt: String,
    /// List of components required by the circuit.
    pub components: Vec<ComponentRequest>,
    /// Logical pin-to-pin connections.
    pub connections: Vec<ConnectionIntent>,
    /// Design constraints extracted from prompt (e.g. "Maintain 90 ohm differential impedance on USB lines").
    pub constraints: Vec<String>,
    /// Whether this intent has passed the real-part validator.
    #[serde(default)]
    pub is_validated: bool,
}

impl CircuitIntent {
    pub fn new(prompt: impl Into<String>) -> Self {
        Self {
            prompt: prompt.into(),
            components: Vec::new(),
            connections: Vec::new(),
            constraints: Vec::new(),
            is_validated: false,
        }
    }

    /// Add a component request.
    pub fn add_component(&mut self, comp: ComponentRequest) {
        self.components.push(comp);
    }

    /// Add a connection intent.
    pub fn add_connection(
        &mut self,
        net_name: impl Into<String>,
        from: (impl Into<String>, impl Into<String>),
        to: (impl Into<String>, impl Into<String>),
    ) {
        self.connections.push(ConnectionIntent {
            net_name: net_name.into(),
            from: (from.0.into(), from.1.into()),
            to: (to.0.into(), to.1.into()),
        });
    }
}
